# Generated by Django 3.1.3 on 2020-11-29 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfind', '0003_usersearch'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='size',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
