# Generated by Django 3.1.3 on 2020-12-21 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfind', '0006_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='id',
        ),
        migrations.AlterField(
            model_name='result',
            name='term',
            field=models.CharField(max_length=4092, primary_key=True, serialize=False),
        ),
    ]
