# Generated by Django 3.1.3 on 2020-12-24 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfind', '0008_auto_20201224_0131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='protein',
            name='id',
        ),
        migrations.AlterField(
            model_name='protein',
            name='acgt_text',
            field=models.CharField(max_length=3200000),
        ),
        migrations.AlterField(
            model_name='protein',
            name='ncbi_name',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
